on:
  pull_request:
    paths: shx.sh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v2
      - run: ./shx.sh pkgxdev/demo
      - run: ./shx.sh pkgxdev/demo   # check cache route works too
